# Generated by Django 3.2.8 on 2021-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='advisor_id',
            field=models.IntegerField(null=True),
        ),
    ]
