# Generated by Django 3.2.8 on 2021-10-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AddField(
            model_name='login',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
